name: ChatSeparator
main: me.khmDev.ChatSeparator.Base
version: 1
database: false
commands:
   all:
      permission: all.command
      permission-message: No tienes permisos <permission>
permissions:
         chatseparator.listenAll:
                 default: op
         all.command:
                 default: op
         chatseparator.visibleAll:
                 default: op
